"""
ml/storage.py

SQLite persistence layer for labeled IMU windows.

Stores every window that has been given a label (either during calibration
or via user feedback during inference).  This table is the single source
of truth for model training and retraining.

Schema — table: labeled_windows
  id           INTEGER  PK autoincrement
  window_id    TEXT     unique identifier generated by feedback.py
  features     TEXT     JSON array of 28 floats (feature vector)
  label        TEXT     "normal" | "tremor"
  source       TEXT     "calibration" | "feedback"
  trained      INTEGER  0 = not yet used in a training run, 1 = used
  timestamp    TEXT     ISO-8601 UTC

Why SQLite:
  - zero setup, single file, works offline
  - survives server restarts
  - supports the simple queries we need (count, filter, fetch all)
  - no external dependency beyond stdlib sqlite3

Why features stored as JSON (not BLOB):
  - 28 floats is tiny (~250 bytes per row)
  - human-readable: you can open the .db in DB Browser and inspect values
  - easy to export to CSV for offline analysis
"""

import json
import os
import sqlite3
import datetime
import threading
from typing import List, Tuple

import numpy as np

from .features import N_FEATURES

_DEFAULT_DB_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "data", "labels.db"
)

_CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS labeled_windows (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    window_id   TEXT    NOT NULL UNIQUE,
    features    TEXT    NOT NULL,
    label       TEXT    NOT NULL CHECK(label IN ('normal', 'tremor')),
    source      TEXT    NOT NULL CHECK(source IN ('calibration', 'feedback')),
    trained     INTEGER NOT NULL DEFAULT 0,
    timestamp   TEXT    NOT NULL
);
"""

# Index on label for fast class-count queries
_CREATE_INDEX_SQL = """
CREATE INDEX IF NOT EXISTS idx_label ON labeled_windows (label);
"""


class LabelStore:
    """
    Thread-safe SQLite store for labeled feature windows.

    One connection per thread via threading.local() — avoids the
    "SQLite objects created in a thread can only be used in that thread"
    error that occurs when a single connection is shared across threads.
    """

    def __init__(self, db_path: str = _DEFAULT_DB_PATH):
        self._db_path = os.path.abspath(db_path)
        os.makedirs(os.path.dirname(self._db_path), exist_ok=True)
        self._local = threading.local()   # per-thread connection cache
        self._write_lock = threading.Lock()  # serialise writes
        self._init_db()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def save_window(self,
                    window_id: str,
                    features: np.ndarray,
                    label: str,
                    source: str) -> bool:
        """
        Persist one labeled window.

        Parameters
        ----------
        window_id : str   Unique ID (e.g. "w_00042")
        features  : ndarray shape (28,)
        label     : "normal" | "tremor"
        source    : "calibration" | "feedback"

        Returns
        -------
        bool  True on success, False if window_id already exists (duplicate).
        """
        if features.shape != (N_FEATURES,):
            raise ValueError(f"Expected (28,) features, got {features.shape}")
        if label not in ("normal", "tremor"):
            raise ValueError(f"label must be 'normal' or 'tremor', got '{label}'")
        if source not in ("calibration", "feedback"):
            raise ValueError(f"source must be 'calibration' or 'feedback', got '{source}'")

        features_json = json.dumps(features.tolist())
        timestamp     = datetime.datetime.utcnow().isoformat() + "Z"

        sql = """
        INSERT OR IGNORE INTO labeled_windows
            (window_id, features, label, source, trained, timestamp)
        VALUES (?, ?, ?, ?, 0, ?)
        """
        with self._write_lock:
            conn = self._conn()
            cur  = conn.execute(sql, (window_id, features_json, label, source, timestamp))
            conn.commit()
            inserted = cur.rowcount == 1

        return inserted

    def get_all_labeled(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Return all labeled windows as arrays ready for sklearn.

        Returns
        -------
        X : np.ndarray, shape (n_samples, 28)  — feature matrix
        y : np.ndarray, shape (n_samples,)     — integer labels
              0 = normal, 1 = tremor
        """
        rows = self._conn().execute(
            "SELECT features, label FROM labeled_windows ORDER BY id"
        ).fetchall()

        if not rows:
            return np.empty((0, N_FEATURES), dtype=np.float32), np.empty(0, dtype=np.int32)

        X = np.array([json.loads(r[0]) for r in rows], dtype=np.float32)
        y = np.array([0 if r[1] == "normal" else 1 for r in rows], dtype=np.int32)
        return X, y

    def get_untrained(self) -> Tuple[np.ndarray, np.ndarray, List[int]]:
        """
        Return windows not yet used in any training run.

        Returns
        -------
        X    : np.ndarray, shape (n, 28)
        y    : np.ndarray, shape (n,)
        ids  : list of database row ids  (pass back to mark_trained)
        """
        rows = self._conn().execute(
            "SELECT id, features, label FROM labeled_windows WHERE trained = 0 ORDER BY id"
        ).fetchall()

        if not rows:
            return (np.empty((0, N_FEATURES), dtype=np.float32),
                    np.empty(0, dtype=np.int32),
                    [])

        ids = [r[0] for r in rows]
        X   = np.array([json.loads(r[1]) for r in rows], dtype=np.float32)
        y   = np.array([0 if r[2] == "normal" else 1 for r in rows], dtype=np.int32)
        return X, y, ids

    def mark_trained(self, row_ids: List[int]) -> None:
        """Flag rows as used in training so retrainer knows what is new."""
        if not row_ids:
            return
        placeholders = ",".join("?" * len(row_ids))
        sql = f"UPDATE labeled_windows SET trained = 1 WHERE id IN ({placeholders})"
        with self._write_lock:
            conn = self._conn()
            conn.execute(sql, row_ids)
            conn.commit()

    def label_counts(self) -> dict:
        """Return {"normal": N, "tremor": M, "total": N+M}."""
        rows = self._conn().execute(
            "SELECT label, COUNT(*) FROM labeled_windows GROUP BY label"
        ).fetchall()
        counts = {r[0]: r[1] for r in rows}
        counts.setdefault("normal", 0)
        counts.setdefault("tremor", 0)
        counts["total"] = counts["normal"] + counts["tremor"]
        return counts

    def untrained_count(self) -> int:
        """How many new labeled windows have arrived since last training run."""
        row = self._conn().execute(
            "SELECT COUNT(*) FROM labeled_windows WHERE trained = 0"
        ).fetchone()
        return row[0]

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _conn(self) -> sqlite3.Connection:
        """Return (or create) the per-thread SQLite connection."""
        if not hasattr(self._local, "conn") or self._local.conn is None:
            self._local.conn = sqlite3.connect(self._db_path, check_same_thread=False)
        return self._local.conn

    def _init_db(self) -> None:
        """Create table and index if they don't exist yet."""
        conn = self._conn()
        conn.execute(_CREATE_TABLE_SQL)
        conn.execute(_CREATE_INDEX_SQL)
        conn.commit()
